### PR TITLE
fix routing issue that was prevent the correct display of the cluster explorer page

### LINKED ISSUE #59: Fix issue with cluster explorer dashboard being overridden by Elemental dashboard view
- Fix issue with cluster explorer dashboard being overridden by Elemental dashboard view

**To reproduce**
- Go to OS management to load Elemental dashboard view
- Go to your local Cluster on the side-menu (so that it loads the cluster explorer view)
- Check that cluster explorer dashboard being overridden by Elemental dashboard view

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #59 

- fix routing issue that was prevent the correct display of the cluster explorer page

**To test**
Go to OS management to load Elemental dashboard view
Go to your local Cluster on the side-menu (so that it loads the cluster explorer view)
Check that cluster explorer dashboard page is showing correctly and not displaying the Elemental dashboard page

### CODE REVIEW

File: pkg/elemental/models/elemental-resource.js [hunk 1]
```diff
@@ -5,4 +5,8 @@ export default class ElementalResource extends SteveModel {
   get listLocation() {
     return createElementalRoute('resource', { resource: this.type });
   }
+
+  get doneRoute() {
```
Comment (richard-cox) [inline pkg/elemental/models/elemental-resource.js:9]: In epinio i also had to override `parentLocationOverride`. From what i remember that handles the resource link in the header of detail/edit resource pages. Worth double checking that you need/don't need that

Comment (aalves08) [reply pkg/elemental/models/elemental-resource.js:29]: @richard-cox just updated the code with https://github.com/rancher/elemental-ui/pull/60/commits/212c54833791cd8549d6d1444c694e0a1d90b8cf. Thanks for the feedback! 🙇

File: pkg/elemental/models/elemental-resource.js [hunk 2]
```diff
@@ -1,8 +1,32 @@
...
   get listLocation() {
     return createElementalRoute('resource', { resource: this.type });
   }
+
+  get detailLocation() {
+    const detailLocation = clone(this._detailLocation);
+
+    detailLocation.params.resource = this.type;
+
+    if (detailLocation.name.includes('namespace')) {
```
Comment (richard-cox) [inline pkg/elemental/models/elemental-resource.js:16]: Only a comment.

Under the hood generic components check the schema to gate features on the type being namespaced

```
const schema = this.$getters['schemaFor'](this.type);
schema?.attributes?.namespaced
```

This is elemental world though, so i'm not sure how encompassing that is. So this is just something to be aware of if you need to do something similar in the future

**Review by richard-cox — APPROVED** [review]
Haven't given this a test, so trusting your own validation!

File: pkg/elemental/models/elemental-resource.js (hunk 2 above)
Comment (aalves08) [reply pkg/elemental/models/elemental-resource.js]: done
